### ISSUE TITLE
[BUG] slightly wrong usage deletes ENTIRE target folder

### ISSUE THREAD

**Issue by the-drunk-coder** [audiotool/pasta#4]
I was trying to copy a dependency repo and made a mistake when it came to the folder syntax. 

I didn't want to copy a specific folder, but the entire repo into the current one.

This was my `pasta.yaml`:

```
keep_dirs: false
deps:
  - url: https://github.com/audiotool/solATool/
    from: /
    to: /
    options:
      ref: tags/0.0.1
```

I thought this would copy the root of the copied repo into the root of my current folder (where `pasta.yaml` resides).

**Expectation**: a notification that my syntax is invalid, or something along these lines.
**Actual behaviour**: The **ENTIRE** parent folder (where `pasta.yaml` resided) was deleted, including the `pasta.yaml`

**Comment by the-drunk-coder** [comment]
Here's the console output:
```
% GITHUB_TOKEN=**** pasta
Copied files from https://github.com/audiotool/solATool/
Error writing results file: error saving pasta.result.yaml: open /home/.../pasta.result.yaml: no such file or directory%      
```

**Comment by the-drunk-coder** [comment]
Correction: 

Using the (more or less) correct syntax, following the readme, also deletes everything, except that it leaves the parent folder intact and writes the `pasta.result.yaml` ...
```
keep_dirs: false
deps:
  - url: https://github.com/audiotool/solATool/
    from: .
    to: .
    options:
      ref: tags/0.0.1
```

Studying the readme a bit more, I understand where my error lies, but I feel like it's a mistake that is easy to make intuitively, and I think there should be a warning before you delete the contents of the entire folder.
