### ISSUE TITLE
[BUG] copying an entire repository doesn't seem to be working

### ISSUE THREAD

**Issue by the-drunk-coder** [audiotool/pasta#5]
I tried to copy an entire repo into a subfolder of my current repo with this pasta file: 

```
keep_dirs: false
deps:
  - url: https://github.com/audiotool/solATool/
    from: .
    to: ./solATool
    options:
      ref: tags/0.0.1
```
Alternate version:
```
keep_dirs: false
deps:
  - url: https://github.com/audiotool/solATool/
    from: .
    to: ./solATool
    include: .*
    options:
      ref: tags/0.0.1
```

**Expectation**: After running pasta, I can find the I entire repository in the specified subfolder.
**Reality**: The subfolder and `pasta.result.yaml` are created, but the subfolder is empty.

**Comment by the-drunk-coder** [comment]
Seems like copying anything from the root folder directly doesn't work ... i tried with this one: 
```
keep_dirs: false
deps:
    - url: https://github.com/audiotool/solATool/
      from: src/
      to: solATool/src/
      options:
          ref: tags/0.0.1

    - url: https://github.com/audiotool/solATool/
      from: .
      to: solATool/
      files:
          - Cargo.toml  
      options:
          ref: tags/0.0.1
```

The first part works, and the `src` folder is copied over. The second one doesn't work, `Cargo.toml` doesn't arrive

**Comment by the-drunk-coder** [comment]
Here's an interesting one: 
```
keep_dirs: false
deps:
    - url: https://github.com/audiotool/solATool
      from: "."
      to: solATool/
      include: "*.*"
      options:
          ref: tags/0.0.1
```

When doing a dry-run:

```
% GITHUB_TOKEN=*** v pasta --dry-run
--dry-run is set, here's what would happen:

Dependency https://github.com/audiotool/solATool:
  Would copy to /home/.../solATool:
    * .gitignore
  Would output:
    reference: cb83a0e6485140a8efb9b39814f8bbf92cfffaf3
    message: safeguard for very small samples
    author:
        date: 2023-11-16T13:40:18Z
        name: ...
        email: ...

```

Chooses gitignore for some reason ...
